export const jobs = [
  {
    id: 1,
    jobTitle: "Full Stack Developer",
    jobDesc:
      "We are looking for a Full Stack Developer to design, develop, and maintain web applications. The role involves both front-end and back-end development.",
    jobLocation: "Gurgaon, NCR",
    payType: "negotiable",
    payInitial: "12",
    payFinal: "15",
    typeOfJob: "part",
    openingDate: "10-08-2024",
    experience: "3-5 years",
    longDesc:
      "As a Full Stack Developer at our company, you will be responsible for designing, developing, and maintaining web applications that are scalable, secure, and user-friendly. Your role will include working closely with our design and product teams to build the best possible user experience. You will be expected to take full ownership of the software development lifecycle, from initial planning to deployment and maintenance. Your responsibilities will include writing clean, maintainable code, implementing responsive design, and ensuring cross-browser compatibility. Additionally, you will work on optimizing applications for maximum speed and scalability, as well as troubleshooting and debugging any issues that arise. You should have a deep understanding of both front-end technologies, like HTML, CSS, and JavaScript, as well as back-end technologies like Node.js and databases. Knowledge of cloud services and continuous integration/continuous deployment (CI/CD) pipelines is a plus. This position offers the opportunity to work on cutting-edge projects and contribute to the development of innovative products.",
    skillsMain: ["JavaScript", "React.js", "Node.js", "SQL"],
    skillsTotal: [
      "JavaScript",
      "React.js",
      "Node.js",
      "SQL",
      "HTML",
      "CSS",
      "Git",
    ],
  },
  {
    id: 2,
    jobTitle: "Data Scientist",
    jobDesc:
      "We are hiring a Data Scientist to analyze large datasets and develop predictive models to drive business decisions.",
    jobLocation: "Noida, NCR",
    payType: "negotiable",
    payInitial: "17",
    payFinal: "21",
    typeOfJob: "full",
    openingDate: "10-08-2024",
    experience: "2-4 years",
    longDesc:
      "As a Data Scientist, you will be at the forefront of our data analytics initiatives, responsible for analyzing large datasets and developing predictive models that drive critical business decisions. You will work closely with cross-functional teams to understand business challenges and identify how data can be leveraged to address them. Your role will involve cleaning and processing data, developing machine learning models, and communicating your findings to stakeholders in a clear and actionable way. You should be proficient in Python or R, have experience with SQL, and be comfortable working with large datasets. Knowledge of cloud platforms such as AWS or Google Cloud, as well as experience with big data technologies like Hadoop or Spark, will be an advantage. You will also be expected to stay updated on the latest trends and advancements in data science and apply them to improve our processes and products.",
    skillsMain: ["Python", "Machine Learning", "Data Analysis", "SQL"],
    skillsTotal: [
      "Python",
      "Machine Learning",
      "Data Analysis",
      "SQL",
      "R",
      "Big Data",
      "Statistics",
    ],
  },
  {
    id: 3,
    jobTitle: "DevOps Engineer",
    jobDesc:
      "We need a DevOps Engineer to automate and streamline operations, build and maintain CI/CD pipelines, and manage cloud infrastructure.",
    jobLocation: "Delhi, NCR",
    payType: "fixed",
    payInitial: "8",
    payFinal: "",
    typeOfJob: "full",
    openingDate: "10-08-2024",
    experience: "3-6 years",
    longDesc:
      "As a DevOps Engineer, your primary responsibility will be to automate and streamline our operations and processes. You will design, build, and maintain CI/CD pipelines that facilitate the continuous delivery of high-quality software. You will also manage and optimize our cloud infrastructure, ensuring that our applications are scalable, secure, and performant. Your day-to-day tasks will include configuring and managing servers, setting up monitoring and logging systems, and ensuring that our deployment processes are efficient and reliable. You should have experience with tools like Jenkins, Docker, Kubernetes, and Terraform, and be familiar with cloud platforms such as AWS, Azure, or Google Cloud. A strong understanding of networking and security principles is also important, as you will be responsible for safeguarding our infrastructure. In this role, you will have the opportunity to work with cutting-edge technologies and contribute to the success of our development and operations teams.",
    skillsMain: ["CI/CD", "Docker", "Kubernetes", "Cloud Infrastructure"],
    skillsTotal: [
      "CI/CD",
      "Docker",
      "Kubernetes",
      "Cloud Infrastructure",
      "Terraform",
      "Jenkins",
      "Networking",
    ],
  },
  {
    id: 4,
    jobTitle: "UI/UX Designer",
    jobDesc:
      "We are seeking a UI/UX Designer to create intuitive and visually appealing user interfaces for our web and mobile applications.",
    jobLocation: "Gurgaon, NCR",
    payType: "negotiable",
    payInitial: "8",
    payFinal: "10",
    typeOfJob: "part",
    openingDate: "10-08-2024",
    experience: "2-4 years",
    longDesc:
      "As a UI/UX Designer, you will be responsible for creating intuitive and visually appealing user interfaces for our web and mobile applications. Your role will involve conducting user research, creating wireframes and prototypes, and collaborating with developers to bring your designs to life. You will need to ensure that our products provide a seamless and engaging user experience, with a focus on usability, accessibility, and visual design. You should have a strong portfolio showcasing your UI/UX design skills, and be proficient in design tools like Sketch, Figma, or Adobe XD. Experience with user testing and understanding of front-end development will be a plus. In this role, you will have the opportunity to work closely with product managers, developers, and other stakeholders to create products that users love.",
    skillsMain: ["UI/UX Design", "Wireframing", "Prototyping", "User Research"],
    skillsTotal: [
      "UI/UX Design",
      "Wireframing",
      "Prototyping",
      "User Research",
      "Sketch",
      "Figma",
      "Adobe XD",
    ],
  },
  {
    id: 5,
    jobTitle: "Cybersecurity Analyst",
    jobDesc:
      "Hiring a Cybersecurity Analyst to monitor, detect, and respond to security threats and protect our company's digital assets.",
    jobLocation: "Noida, NCR",
    payType: "negotiable",
    payInitial: "11",
    payFinal: "14",
    typeOfJob: "internship",
    openingDate: "10-08-2024",
    experience: "3-5 years",
    longDesc:
      "As a Cybersecurity Analyst, you will be responsible for monitoring, detecting, and responding to security threats, ensuring that our company's digital assets are protected. Your role will include analyzing security incidents, implementing security measures, and maintaining our cybersecurity tools and systems. You should have a strong understanding of security principles, network security, and incident response. Experience with security tools like firewalls, intrusion detection/prevention systems (IDS/IPS), and SIEM (Security Information and Event Management) solutions is essential. You will also be expected to stay updated on the latest cybersecurity threats and trends, and work proactively to safeguard our infrastructure. This role is critical to maintaining the integrity and security of our systems, and you will work closely with other IT and security professionals to achieve this goal.",
    skillsMain: [
      "Cybersecurity",
      "Network Security",
      "Incident Response",
      "SIEM",
    ],
    skillsTotal: [
      "Cybersecurity",
      "Network Security",
      "Incident Response",
      "SIEM",
      "IDS/IPS",
      "Firewalls",
      "Threat Analysis",
    ],
  },
];
